name: CI/CD for API de Festivos

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy API de Festivos
    runs-on: ubuntu-latest

    env:
      DOCKER_NETWORK: redcalendario

    steps:
      # Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Crear red Docker (si no existe)
      - name: Create Docker network
        run: |
          docker network inspect $DOCKER_NETWORK || docker network create $DOCKER_NETWORK

      # Construir y contenerizar API de Festivos
      - name: Build and deploy API de Festivos
        run: |
          docker build -t apifestivos-master .
          docker stop dockerapiapifestivos-master || true
          docker rm dockerapiapifestivos-master || true
          docker run --network $DOCKER_NETWORK --name dockerapiapifestivos-master -p 3000:8080 -d apifestivos-master

      # Verificar que el contenedor esté corriendo
      - name: Verify container
        run: |
          docker ps -a | grep dockerapiapifestivos-master
